[package]
name = "windows"
version.workspace = true
edition.workspace = true
authors = { workspace = true }
license = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "firehol-differ-nftables"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
firehol = { package = "firehol", path = "../firehol" }
log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
windows-sys = { version = "0.61", features = ["Win32_System_EventLog"] }
