[Service]
ExecStartPost=/bin/sh -c 'pid=$(systemctl show --property=MainPID --value firehol-differ-nftables.service); if [ "$pid" -gt 0 ]; then kill -USR1 "$pid"; fi'
ExecReload=/bin/sh -c 'pid=$(systemctl show --property=MainPID --value firehol-differ-nftables.service); if [ "$pid" -gt 0 ]; then kill -USR1 "$pid"; fi'
